import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Northwest Therapeutic Massage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3pro.css"></link>
      </Head>

      <main className={styles.main}>
        <h1>Welcome to Northwest Therapeutic Massage</h1>
        <h2>Michael Kaplan LMT</h2>
        <p>We strive to work with you and your medical professional to provide the best custom tailored massages. Whether it is for relaxation and stress reduction or therapy treatments from an accident or surgery we are here to help you.</p>
        <ul>Our services include:
        <li>Ultimate Relaxation</li>
          <li>Auto Accident recovery</li>
          <li>Post surgery treatments</li>
          <li>Stress reduction</li>
          <li>Workplace injury recovery</li>
          <li>Pain reduction</li>
          <li>and so much more!</li>
        </ul>
        <h1>Now offering on-site massage services at your home or location</h1>
        <h3>on-site massages within seattle, bellevue, or greater east side area</h3>
        <ul>Service location:
          <li>12951 Bel-Red Road, Suite 100</li>
          <li>Bellevue Washington 98005,</li>
          <li>BY APPOINTMENT ONLY</li>
          <li>No walk in accepted</li>
        </ul>
      </main>
    </div>
  )
}
